version: 1
policy:
  pullRequests: public
tasks:
  - $if: '(tasks_for == "github-pull-request"  && event["action"] in ["opened", "reopened", "synchronize"])'
    then:
      taskId: { $eval: as_slugid("test") }
      created: { $fromNow: "" }
      deadline: { $fromNow: "2 hours" }
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      payload:
        maxRunTime: 3600
        image: taskcluster/monopacker:build
        command:
          - /bin/bash
          - --login
          - -cx
          - |
            CHECKOUT_DIR="/monopacker_checkout"
            git clone "${event.pull_request.head.repo.clone_url}" "$CHECKOUT_DIR"
            cd "$CHECKOUT_DIR"
            git checkout "${event.pull_request.head.sha}"
            pipenv install
            pipenv run make validate
            pipenv run make test
      metadata:
        name: monopacker tests
        description: runs tests, validates default packer builders
        owner: taskcluster-internal@mozilla.com
        source: ${event.pull_request.head.repo.clone_url}
  - $if: 'tasks_for == "github-push"'
    then:
      taskId: { $eval: as_slugid("test") }
      created: { $fromNow: "" }
      deadline: { $fromNow: "2 hours" }
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      payload:
        maxRunTime: 3600
        image: taskcluster/monopacker:build
        command:
          - /bin/sh
          - --login
          - -cx
          - |
            CHECKOUT_DIR="/monopacker_checkout"
            git clone "${event.repository.url}" "$CHECKOUT_DIR"
            cd "$CHECKOUT_DIR"
            git checkout "${event.after}"
            pipenv install
            pipenv run make validate
            pipenv run make test
      metadata:
        name: monopacker tests
        description: runs tests, validates default packer builders
        owner: taskcluster-internal@mozilla.com
        source: ${event.repository.url}
