version: 1
policy:
  pullRequests: public
tasks:
  - $if: '(tasks_for == "github-pull-request"  && event["action"] in ["opened", "reopened", "synchronize"])'
    then:
      taskId: { $eval: as_slugid("test") }
      created: { $fromNow: "" }
      deadline: { $fromNow: "2 hours" }
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      payload:
        maxRunTime: 3600
        image: taskcluster/monopacker:build
        command:
          - /bin/bash
          - --login
          - -cx
          - |
            CHECKOUT_DIR="/monopacker_checkout"
            git clone "${event.pull_request.head.repo.clone_url}" "$CHECKOUT_DIR"
            cd "$CHECKOUT_DIR"
            git checkout "${event.pull_request.head.sha}"
            pipenv install
            pipenv run make validate
            pipenv run make test
      metadata:
        name: monopacker tests
        description: runs tests, validates default packer builders
        owner: taskcluster-internal@mozilla.com
        source: ${event.pull_request.head.repo.clone_url}
  - $if: 'tasks_for == "github-push"'
    then:
      taskId: { $eval: as_slugid("test") }
      created: { $fromNow: "" }
      deadline: { $fromNow: "2 hours" }
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      payload:
        maxRunTime: 3600
        image: taskcluster/monopacker:build
        command:
          - /bin/bash
          - --login
          - -cx
          - |
            CHECKOUT_DIR="/monopacker_checkout"
            git clone "${event.repository.url}" "$CHECKOUT_DIR"
            cd "$CHECKOUT_DIR"
            git checkout "${event.after}"
            pipenv install
            pipenv run make validate
            pipenv run make test
      metadata:
        name: monopacker tests
        description: runs tests, validates default packer builders
        owner: taskcluster-internal@mozilla.com
        source: ${event.repository.url}
  - $if: '(true || tasks_for == "github-push" && event.ref == "refs/heads/master")'
    then:
      taskId: { $eval: as_slugid("bake") }
      created: { $fromNow: "" }
      deadline: { $fromNow: "2 hours" }
      provisionerId: taskcluster-imaging
      workerType: taskcluster-imaging-ci
      payload:
        maxRunTime: 3600
        image: taskcluster/monopacker:build
        command:
          - /bin/bash
          - --login
          - -cx
          - |
            CHECKOUT_DIR="/monopacker_checkout"
            git clone "${event.repository.url}" "$CHECKOUT_DIR"
            cd "$CHECKOUT_DIR"
            git checkout "${event.after}"
            curl $TASKCLUSTER_PROXY_URL/api/secrets/v1/secret/project/taskcluster/monopacker/image_baking
            pipenv install
            pipenv run make build BUILDERS="docker_worker_gcp"
        artifacts:
          "packer-artifacts.json":
            type: file
            path: /monopacker_checkout/packer-artifacts.json
            expires: 3019-01-26T22:59:45.539Z
      metadata:
        name: bake images
        description: bake docker_worker_gcp and docker_worker_gcp_l3 images
        owner: taskcluster-internal@mozilla.com
        source: ${event.repository.url}
