#!/usr/bin/env python3

import subprocess
import platform
import argparse
import os
from datetime import datetime
from zoneinfo import ZoneInfo

VERSION = "1.0.1"

def get_system_info():
    info = {
        'OS': platform.system(),
        'OS Version': platform.version(),
        'Architecture': platform.machine(),
        'Processor': platform.processor(),
        'Python Version': platform.python_version(),
        'Kernel Version': subprocess.run(['uname', '-r'], stdout=subprocess.PIPE, text=True).stdout.strip()
    }
    return info

def get_lsb_release_info():
    lsb_info = {}
    try:
        with open('/etc/lsb-release', 'r') as file:
            lsb_data = file.readlines()
            for line in lsb_data:
                key, value = line.strip().split('=')
                lsb_info[key] = value
    except FileNotFoundError:
        lsb_info['LSB Release'] = 'Not available'
    return lsb_info

def get_os_release_info():
    os_info = {}
    try:
        with open('/etc/os-release', 'r') as file:
            os_data = file.readlines()
            for line in os_data:
                key, value = line.strip().split('=')
                os_info[key] = value.strip('"')
    except FileNotFoundError:
        os_info['OS Release'] = 'Not available'
    return os_info

def get_taskcluster_info():
    taskcluster_info = {}
    commands = {
        'generic-worker': ['generic-worker', '--version'],
        'taskcluster-proxy': ['taskcluster-proxy', '--version'],
        'livelog': ['livelog', '--version'],
        'start-worker': ['start-worker', '--version']
    }
    
    for key, command in commands.items():
        try:
            result = subprocess.run(command, stdout=subprocess.PIPE, text=True, timeout=1)
            taskcluster_info[key] = result.stdout.strip()
        except (FileNotFoundError, subprocess.TimeoutExpired):
            taskcluster_info[key] = 'Not available'
    
    return taskcluster_info

def get_installed_packages():
    result = subprocess.run(['dpkg', '-l'], stdout=subprocess.PIPE, text=True)
    packages = []
    for line in result.stdout.split('\n')[5:]:
        if line:
            parts = line.split()
            packages.append({
                'Name': parts[1],
                'Version': parts[2],
                'Architecture': parts[3],
            })
    return packages

def get_pip_packages():
    result = subprocess.run(['pip3', 'list'], stdout=subprocess.PIPE, text=True)
    packages = []
    for line in result.stdout.split('\n')[2:]:
        if line:
            parts = line.split()
            name = parts[0]
            version = parts[1]
            packages.append({
                'Name': name,
                'Version': version
            })
    return packages

def generate_markdown(sbom):
    md = []
    md.append(f"# Software Bill of Materials (SBOM)")
    
    if sbom.get('monopacker_builder_name'):
        md.append(f"- **Monopacker Builder Name**: {sbom['monopacker_builder_name']}")
    if sbom.get('monopacker_commit'):
        commit_url = f"https://github.com/search?q=repo%3Amozilla-platform-ops%2Fmonopacker+{sbom['monopacker_commit']}&type=code"
        md.append(f"- **Monopacker Commit**: [{sbom['monopacker_commit']}]({commit_url})")
    md.append(f"- **SBOM Generated By**: {sbom['generated_by']} {VERSION}")
    md.append(f"- **SBOM Generation Datetime**: {sbom['generated_on']} {sbom['timezone']}")
    
    md.append(f"\n## System Information")
    md.append(f"Information obtained using Python's `platform` module and `uname -r` command.")
    for key, value in sbom['system_info'].items():
        md.append(f"- **{key}**: {value}")
    
    md.append(f"\n## LSB Release Information")
    md.append(f"Information obtained from `/etc/lsb-release` file.")
    for key, value in sbom['lsb_release_info'].items():
        md.append(f"- **{key}**: {value}")

    md.append(f"\n## OS Release Information")
    md.append(f"Information obtained from `/etc/os-release` file.")
    for key, value in sbom['os_release_info'].items():
        md.append(f"- **{key}**: {value}")
    
    if sbom.get('additional_info'):
        md.append(f"\n## Additional Information")
        for key, value in sbom['additional_info'].items():
            md.append(f"- **{key}**: {value}")

    md.append(f"\n## Taskcluster Information")
    md.append(f"Information obtained using the respective tool's `--version` command with a 1-second timeout.")
    md.append(f"| Tool            | Version     |")
    md.append(f"|-----------------|-------------|")
    for key, value in sbom['taskcluster_info'].items():
        md.append(f"| {key} | {value} |")
    
    md.append(f"\n## Installed Packages")
    md.append(f"Information obtained using `dpkg -l` command.")
    md.append(f"| Name | Version | Architecture |")
    md.append(f"|------|---------|--------------|")
    for pkg in sbom['packages']:
        md.append(f"| {pkg['Name']} | {pkg['Version']} | {pkg['Architecture']} |")
    
    md.append(f"\n## Python Packages")
    md.append(f"Information obtained using `pip3 list` command.")
    md.append(f"| Name | Version |")
    md.append(f"|------|---------|")
    for pkg in sbom['pip_packages']:
        md.append(f"| {pkg['Name']} | {pkg['Version']} |")
    
    return '\n'.join(md)

def main():
    parser = argparse.ArgumentParser(description="Generate a markdown-formatted SBOM for a Ubuntu system.")
    parser.add_argument('-b', '--monopacker_builder_name', type=str, required=True, help='Name of the monopacker builder')
    parser.add_argument('-c', '--monopacker_commit', type=str, required=True, help='Commit of the monopacker')
    parser.add_argument('-a', '--additional-key-value', action='append', help='Additional key-value pairs to add to system info in the format key,value')
    
    args = parser.parse_args()
    
    system_info = get_system_info()
    lsb_release_info = get_lsb_release_info()
    os_release_info = get_os_release_info()
    taskcluster_info = get_taskcluster_info()
    
    additional_info = {}
    if args.additional_key_value:
        for item in args.additional_key_value:
            key, value = item.split(',', 1)
            additional_info[key.strip()] = value.strip()
    
    packages = get_installed_packages()
    pip_packages = get_pip_packages()
    
    now = datetime.now(ZoneInfo("UTC"))
    timezone = now.astimezone().strftime('%Z %z')
    sbom = {
        'system_info': system_info,
        'lsb_release_info': lsb_release_info,
        'os_release_info': os_release_info,
        'taskcluster_info': taskcluster_info,
        'additional_info': additional_info,
        'packages': packages,
        'pip_packages': pip_packages,
        'monopacker_builder_name': args.monopacker_builder_name,
        'monopacker_commit': args.monopacker_commit,
        'generated_on': now.astimezone().strftime("%Y-%m-%d %H:%M:%S"),
        'timezone': timezone,
        'generated_by': os.path.basename(__file__)
    }
    
    markdown_content = generate_markdown(sbom)
    
    with open('SBOM.md', 'w') as f:
        f.write(markdown_content)
    
    print("SBOM has been generated and saved to SBOM.md")

if __name__ == "__main__":
    main()